# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-24 15:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_friendship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
