# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180116_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
