# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-16 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180116_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('dob', models.DateField()),
                ('hiredate', models.DateField()),
                ('mgrno', models.IntegerField()),
                ('gender', models.IntegerField(help_text=b'1 for male and 2 for female')),
                ('deptno', models.IntegerField()),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.City')),
            ],
        ),
    ]
